### ISSUE TITLE
Please write region names in nominative (ονομαστική) not in genitive (γενική)

### ISSUE THREAD

**Issue by cptX** [magevision/magento2-greek-regions#1]
Please write region names in nominative (ονομαστική) not in genitive (γενική) as in certain circumstances will not show correctly. For example in an email the shop address will include the State (in my case I don't even need the State but magento 2 has no way to remove it from the email). So with the state included without this module looks like:

test company
Ταδε 12
Αθήνα, Attikí 11526,
Ελλάδα

And with your module will appear as:

test company
Ταδε 12
Αθήνα, Αττικής 11526,
Ελλάδα

It would be nicer if it would appear as 

test company
Ταδε 12
Αθήνα, Αττική 11526,
Ελλάδα

so in nominative form (Αττική) is more correct than in genitive form (Αττικής)

**Comment by magevision** [comment]
In the checkout the greek translation about the state to select is "Νομός" which is in genitive (γενική). So there it will be wrong if we change it to nominative (ονομαστική). There is also a way to remove the state from the address email (but also for all the html templates), by removing it from the HTML addresses templates in system configuration.

**Comment by magevision** [comment]
In the checkout the greek translation about the state to select is "Νομός" which is in genitive (γενική). So there it will be wrong if we change it to nominative (ονομαστική). There is also a way to remove the state from the address email (but also for all the html templates), by removing it from the HTML addresses templates in system configuration.

**Comment by magevision** [comment]
In the checkout the greek translation about the state to select is "Νομός" which is in genitive (γενική). So there it will be wrong if we change it to nominative (ονομαστική). There is also a way to remove the state from the address email (but also for all the html templates), by removing it from the HTML addresses templates in system configuration.

**Comment by magevision** [comment]
In the checkout the greek translation about the state to select is "Νομός" which is in genitive (γενική). So there it will be wrong if we change it to nominative (ονομαστική). There is also a way to remove the state from the address email (but also for all the html templates), by removing it from the HTML addresses templates in system configuration.

**Comment by cptX** [comment]
Thanks for giving feedback on this. Yes I need to create new templates for removing the Region from the address in the email , but is such a pity needing to create a new template just to remove a single word..

As I'm not using region for Greece at the moment I'm not sure, but who is writing the region as "Νομος" and not as "Περιοχή" in the current implementation? Is your module doing the translation to "Νομός"? What if you renamed to "Περιοχή"? This maybe could justify the use of nominative. Anyway if you don't consider it important don't change it but please understand that it is also used in addresses and there genitive cannot be used...

**Comment by magevision** [comment]
If you do not need the region at all why you don't deactivate it in the configuration? So at least the new customer addresses will not have any region. No, our extension does not do any translations but if you use for example the Greek language pack from https://github.com/mageplaza/magento-2-greek-language-pack probably you will get is as "Νομός".

**Comment by cptX** [comment]
I have deactivated it of course and indeed customers don't get asked about region, but when an email is sent to a customer from the system the region is added to the shop's address, which is bad because the address is in greek and the region in greeklish!!

Can you give us an example of how your shop address is shown in an email sent to a customer with your implementation?

**Comment by magevision** [comment]
In the email template is like yours in Greek language

Όνομα Επώνυμο
Διεύθυνση 34
Aθήνα, Αττικής, 12345
Ελλάδα
T: [12345](tel:12345)

**Comment by cptX** [comment]
OK, you see now my point I hope. If you think of any better solution please tell.
